export const gumTape = [
  {
    id: 1,
    title: 'Gum Tape of 2024',
    image:
      'https://gumtapebd.com/wp-content/uploads/2023/11/Gum-Tape-Price-in-Bangladesh.jpg',
    brand: 'Alpha',
    width: '60mm - 50 Yard',
    thickness: '40 Micron',
    quality: 'Premium',
    madeIn: 'Bangladesh',
  },
  {
    id: 2,
    title: 'Best Gum Tape for Packaging',
    image:
      'https://gumtapebd.com/wp-content/uploads/2022/11/Gum-Tape-Manufacturer-in-Bangladesh-11.jpg',
    brand: 'Scotia',
    width: '57mm – 120 Yard',
    thickness: '40 Micron',
    quality: 'Good Quality',
    madeIn: 'Bangladesh',
  },
  {
    id: 3,
    title: 'Best Gum Tape for Packaging',
    image:
      'https://gumtapebd.com/wp-content/uploads/2023/11/Gum-Tape-Price-in-Bangladesh-2.jpg',
    brand: 'Scotia',
    width: '57mm – 80 Yard',
    thickness: '40 Micron',
    quality: 'Good Quality',
    madeIn: 'Bangladesh',
  },
  {
    id: 4,
    title: 'Best Packaging Tape Size',
    image:
      'https://gumtapebd.com/wp-content/uploads/2023/11/Gum-Tape-Factory-in-Bangladesh-3.jpg',
    brand: 'Scotia',
    width: '60mm – 80 Yard',
    thickness: '40 Micron',
    quality: 'Good Quality',
    madeIn: 'Bangladesh',
  },
  {
    id: 5,
    title: 'Best Stationery Tapes',
    image:
      'https://gumtapebd.com/wp-content/uploads/2024/01/Stationery-tape-price-in-Bangladesh-1.jpg',
    // brand: "Scotia",
    width: '18mm – 25 Yard',
    thickness: '40 Micron',
    quality: 'Good Quality',
    madeIn: 'Bangladesh',
  },
  {
    id: 6,
    title: 'Rexine Tape of 2024',
    image:
      'https://gumtapebd.com/wp-content/uploads/2024/01/Rexine-tape-price-in-Bangladesh-7.jpg',
    brand: 'Hunter Rexine Tape',
    width: '48mm – 10 Yard',
    thickness: '40 Micron',
    quality: 'Good Quality',
    madeIn: 'Bangladesh',
  },
  {
    id: 7,
    title: 'Best Scotch Packaging Tape',
    image:
      'https://gumtapebd.com/wp-content/uploads/2023/11/Gum-Tape-Factory-in-Bangladesh-4.jpg',
    brand: 'Scotia Tape',
    width: '57mm – 400 Yard',
    thickness: '40 Micron',
    quality: 'Good Quality',
    madeIn: 'Bangladesh',
  },
  {
    id: 8,
    title: 'Gum Tapes Jumbo Roll',
    image:
      'https://gumtapebd.com/wp-content/uploads/2023/11/Gum-Tape-Price-in-Bangladesh-3.jpg',
    brand: 'Scotia',
    width: '57mm – 500 Yard',
    thickness: '40 Micron',
    quality: 'Good Quality',
    madeIn: 'Bangladesh',
  },
  {
    id: 9,
    title: 'Best Packaging Tape of 2024',
    image:
      'https://gumtapebd.com/wp-content/uploads/2023/11/Gum-Tape-Manufacturer-in-Bangladesh-1.jpg',
    brand: 'Scotia',
    width: '57mm – 50 Yard',
    thickness: '40 Micron',
    quality: 'Good Quality',
    madeIn: 'Bangladesh',
  },
  {
    id: 10,
    title: 'Best Gum Tape Price',
    image:
      'https://gumtapebd.com/wp-content/uploads/2022/11/Gum-Tape-Factory-in-Bangladesh.jpg',
    brand: 'Scotia Tape',
    width: '57mm – 100 Yard',
    thickness: '40 Micron',
    quality: 'Good Quality',
    madeIn: 'Bangladesh',
  },
  {
    id: 11,
    title: 'Best Packaging Tape Manufacturer',
    image: 'https://gumtapebd.com/wp-content/uploads/2023/11/Gum-Tape-.jpg',
    brand: 'Scotia',
    width: '24mm – 70 Yard',
    thickness: '40 Micron',
    quality: 'Good Quality',
    madeIn: 'Bangladesh',
  },
  {
    id: 12,
    title: 'Double Sided Tape Price in Bangladesh of 2024',
    image:
      'https://gumtapebd.com/wp-content/uploads/2023/11/Double-sided-Tape-Both-Sided-Tape.jpg',
    brand: 'Nikto Tape',
    width: '24mm – 35 Yard',
    thickness: '130 Micron',
    quality: 'Good Quality',
    madeIn: 'Bangladesh',
  },
  {
    id: 13,
    title: 'Reinforced Paper Gum Tape',
    image:
      'https://gumtapebd.com/wp-content/uploads/2023/11/Adhesive-Paper-Tape-Price-in-Bangladesh.jpg',
    brand: 'Nikto/ Hunter',
    width: '60mm – 40 Yard',
    thickness: '130 Micron',
    quality: 'Good Quality',
    madeIn: 'Bangladesh',
  },
  {
    id: 14,
    title: 'Best Masking Tape Price',
    image:
      'https://gumtapebd.com/wp-content/uploads/2023/11/Masking-Tape-Masking-Tape-Price-in-bangladesh.jpg',
    brand: 'Hunter',
    width: '48mm – 20 Yard',
    thickness: '110 Micron',
    quality: 'Good Quality',
    madeIn: 'Bangladesh',
  },
  {
    id: 15,
    title: 'Water Activated Gum Paper Tape',
    image:
      'https://gumtapebd.com/wp-content/uploads/2023/11/Paper-Tape-Kraft-Paper-Tape-Paper-Tape-Price.jpg',
    // brand: "Hunter",
    width: '72mm – 40 Yard',
    Logo: 'As per customer’s choice',
    // thickness: "110 Micron",
    quality: 'Good Quality',
    madeIn: 'Bangladesh',
  },
  {
    id: 16,
    title: 'Brown Packaging Tapes of 2024',
    image:
      'https://gumtapebd.com/wp-content/uploads/2022/11/Gum-Tape-Manufacturer-in-Bangladesh-10.jpg',
    brand: 'Scotia Tapes',
    width: '57mm – 70 Yard',
    thickness: '40 Micron',
    quality: 'Good Quality',
    madeIn: 'Bangladesh',
  },
  {
    id: 17,
    title: 'Custom Packaging Tapes',
    image:
      'https://gumtapebd.com/wp-content/uploads/2023/12/Gum-Tape-Price-in-Bangladesh-7.jpg',
    brand: 'Scotia Tapes',
    width: '57mm – 100 Yard',
    thickness: '40 Micron',
    quality: 'Good Quality',
    madeIn: 'Bangladesh',
  },
  {
    id: 18,
    title: 'Best Double Side Tape of 2024',
    image:
      'https://gumtapebd.com/wp-content/uploads/2024/03/Both-side-tapes.jpg',
    brand: 'Hunter',
    width: '48mm – 50 Yard',
    thickness: '90 Micron',
    quality: 'Good Quality',
    madeIn: 'Bangladesh',
  },
]
